module.exports = [ { pCode: 'P1', carCode: 'S1-A-3', step: 2 },
     { pCode: 'P2', carCode: 'S1-A-2', step: 2 },
     { pCode: 'P3', carCode: 'S1-A-3', step: 1 },
     { pCode: 'P4', carCode: 'S1-B-2', step: 2 },
     { pCode: 'P5', carCode: 'S1-A-2', step: 1 },
     { pCode: 'P6', carCode: 'S1-A-3', step: 3 },
     { pCode: 'P7', carCode: 'S1-A-1', step: 2 },
     { pCode: 'P8', carCode: 'S1-A-1', step: 1 },
     { pCode: 'P9', carCode: 'S1-B-2', step: 1 },
     { pCode: 'P10', carCode: 'S1-C-1', step: 1 },
     { pCode: 'P11', carCode: 'S1-C-1', step: 2 } ]